Repository cuculus-dev/cuculus-roadmap, pull requests merged in 2023-09, with the labels that each got.

#48 カードの新規作成
  .gitignore
  public/images/active.svg
  public/images/marged.svg
  src/app/_components/Issues.stories.ts
  src/app/_components/Issues.tsx
  src/app/_components/Milestones.stories.ts
  src/app/_components/Milestones.tsx
  src/app/_components/MilestonesSample.tsx
  src/app/page.tsx
  src/components/common/organisms/Card.stories.ts
  src/components/common/organisms/Card.tsx
  src/components/common/organisms/SkeltonCard.stories.ts
  src/components/common/organisms/SkeltonCard.tsx
  src/swr/client/issues.ts
Labels: feature, nomerge

#22 デプロイ先をGitHub Pagesに変更
  .github/workflows/nextjs.yml
  next.config.js
Labels: develop, nomerge

#45 画面左側の要素を移動する
  src/app/_components/Caption.tsx
  src/app/page.tsx
Labels: help wanted, feature
